### ISSUE TITLE
DoctrineDataCollector errors when second level cache logging is disabled

### ISSUE THREAD

**Issue by evertharmeling** [doctrine/DoctrineBundle#1250]
Version: 2.2.x

I get the following error:

```
AssertionError

assert($cacheLoggerChain instanceof CacheLoggerChain)

in vendor/doctrine/doctrine-bundle/DataCollector/DoctrineDataCollector.php (line 104)
```

Introduced with https://github.com/doctrine/DoctrineBundle/commit/50c53bef10617dc3c3e8e279f3be6b4e38abc8f6

This is my current configuration: `doctrine.yaml`
```
doctrine:
  ...
  orm:
        ...
        second_level_cache:
            enabled:         true
            log_enabled:  false
```

It looks like the `assert` statement isn't correct as when you have logging disabled, this would bypass the following configuration in https://github.com/doctrine/DoctrineBundle/blob/2.2.x/DependencyInjection/DoctrineExtension.php#L730-L746 and therefore the `$cacheLoggerChain` variable will not be set and would explain the error.

Possible solution:
- Remove `assert($cacheLoggerChain instanceof CacheLoggerChain)` line in https://github.com/doctrine/DoctrineBundle/blob/2.2.x/DataCollector/DoctrineDataCollector.php#L104 as on https://github.com/doctrine/DoctrineBundle/blob/2.2.x/DataCollector/DoctrineDataCollector.php#L106 there already is a check.
- Or introduce a 'NullCacheLogger' object (equivalent to https://github.com/php-fig/log/blob/master/Psr/Log/NullLogger.php) and have that set in the definition.

Related to: https://github.com/doctrine/DoctrineBundle/issues/1247

**Comment by stof** [comment]
I think that this was because the old phpdoc was wrong about the type, saying it was `CacheLoggerChain` while the actual type was `CacheLoggerChain|null` at least

**Comment by ostrolucky** [comment]
Can you try if https://github.com/doctrine/DoctrineBundle/pull/1248 fixes the problem?

**Comment by ostrolucky** [comment]
Fixed in 2.2.1

**Comment by evertharmeling** [comment]
Unfortunately, that does not solve it...

Because `$cacheConfiguration` is not `null` it's an instance of `Doctrine\ORM\Cache\CacheConfiguration` :)

Following line works
```
assert($cacheLoggerChain instanceof CacheLoggerChain || $cacheLoggerChain === null);
```

**Comment by ostrolucky** [comment]
I don't understand, which assertion is failing now?

**Comment by evertharmeling** [comment]
Sorry, I'll try to be more exact, what caused the error originally was:
```
assert($cacheLoggerChain instanceof CacheLoggerChain)
```
Because `$cacheLoggerChain` can be `CacheLoggerChain|null`

The change in https://github.com/doctrine/DoctrineBundle/pull/1248 was (also errored):
```
assert($cacheLoggerChain instanceof CacheLoggerChain || $cacheConfiguration === null);
```
Probably the variable `$cacheConfiguration` was mistaken with `$cacheLoggerChain`

Proposed change would be:
```
assert($cacheLoggerChain instanceof CacheLoggerChain || $cacheLoggerChain === null);
```

See https://github.com/doctrine/DoctrineBundle/blob/2.2.x/DataCollector/DoctrineDataCollector.php#L104

**Comment by ostrolucky** [comment]
🤦 I see

**Comment by ostrolucky** [comment]
Fix was pushed in 2.2.x branch, will be fixed with next release

**Comment by evertharmeling** [comment]
Thanks!
