### ISSUE TITLE
ContextErrorException from console doctrine:generate:entities when using custom EntityManager

### ISSUE THREAD

**Issue by blackgearit** [doctrine/DoctrineBundle#403]
I've setup a custom EntityManager decorating it with \Doctrine\ORM\Decorator\EntityManagerDecorator. All works except command line 
php app/console doctrine:generate:entities myBundle 
that raises 
 
[Symfony\Component\Debug\Exception\ContextErrorException]                                                                                    
Catchable Fatal Error: Argument 1 passed to Doctrine\ORM\Mapping\ClassMetadataFactory::setEntityManager() must be an instance of Doctrine\ORM\EntityManager, instance of myBundle\Doctrine\myManager given, called in /vendor/doctrine/doctrine-bundle/Mapping/DisconnectedMetadataFactory.php on line 201 and defined
 
I've changed the /vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php method setEntityManager from
public function setEntityManager(EntityManager $em)
to
public function setEntityManager(\Doctrine\ORM\EntityManagerInterface $em)
and command line works again.
I've tried to insert some echoes in DesconnectedMetadataFactory to check myManager's class 
echo get_class($em); // returns myBundle/Doctrine/myManager
echo ($em instanceof \Doctrine\ORM\EntityManager)?"1":"0"); // returns 0
echo (is_subclass_of($em,'Doctrine\ORM\EntityManager')?"1":"0"); // returns 0
I've not found any exaustive documentation about custom EntityManager, so this is the only solution I've found.

**Comment by sketchmedia** [comment]
This is an issue with the version of Doctrine ORM you have installed, not the bundle itself.

As far as I can see, this was resolved in 2.5? https://github.com/doctrine/doctrine2/commit/e65417f1f618c47f8df6abf235ffc5c075d34702

**Comment by deeky666** [comment]
@blackgearit yes as @sketchmedia pointed out, you'll have to use ORM 2.5 for that as `EntityManagerInterface` support was not fully introduced all over ORM and still isn't.
Please see the 2.5 changes [here](http://doctrine-orm.readthedocs.org/en/latest/changelog/migration_2_5.html#better-support-for-entitymanagerinterface)
