### ISSUE TITLE
DoctrineCommand class extends the deprecated ContainerAwareCommand class

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/DoctrineBundle#863]
Spotted while upgrading the Symfony Demo app to 4.2.x-dev:

```
The "Doctrine\Bundle\DoctrineBundle\Command\DoctrineCommand" class extends 
"Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" that is
deprecated since Symfony 4.2, use Command instead.
```

**Comment by Ocramius** [comment]
Not sure if the inheritance can be removed without this being called a
major BC break though...

**Comment by chalasr** [comment]
The type change is technically BC breaking, but who injects (or perform `instanceof` checks on) commands...  `DoctrineCommand` could still provide the `getContainer()`  and `setContainer()` methods for a time (forever if we don't want to make them to use true DI at some point), even implement `ContainerAwareInterface`. 

I'd assume the BC break here. It has been done for swiftmailer-bundle in https://github.com/symfony/swiftmailer-bundle/pull/262, I can do the PR in case we agree.

**Comment by chalasr** [comment]
Fixed in #877

**Comment by DerDu** [comment]
Hm.. using 4.2.x somehow is still get the deprecated message from "symfony/orm-pack": "*"
if i do `composer unpack orm` it shows
```
"doctrine/doctrine-bundle": "^1.6.10",
"doctrine/doctrine-migrations-bundle": "^1.3|^2.0",
"doctrine/orm": "^2.5.11",
```
and installed 1.10.2

But if i go for something like this:
```
<?php
namespace App\Tests;
[...]
use Symfony\Bundle\FrameworkBundle\Client;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;
[...]
class Test extends WebTestCase {

    public static function setUpBeforeClass(): void
    {
        $kernel = self::bootKernel();

        $app = new Application($kernel);
        $app->setAutoExit(false);

        $out = new BufferedOutput();
        $in = new ArrayInput([
            'command' => 'doctrine:schema:create'
        ]);
        $app->run($in, $out);

        $out = new BufferedOutput();
        $in = new ArrayInput([
            'command' => 'doctrine:fixtures:load',
            '--no-interaction' => null
        ]);
        $app->run($in, $out);

        parent::setUpBeforeClass();
    }
}
```
it gives me:

>   1x: The "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" class is deprecated since Symfony 4.2, use "Symfony\Component\Console\Command\Command" with dependency injection instead.
    1x in AbstractTest::setUpBeforeClass from App\Tests

am i doing it wrong perhaps?
